language: node_js

node_js:
  - "5"

sudo: false

before_script:
  - npm install -g eslint istanbul
  - npm install
  - npm install coveralls

script: npm run test:coveralls

branches:
  except:
    - gh-pages
